/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package isenkdoank.marikost.view;

import isenkdoank.marikost.controller.Data;
import isenkdoank.marikost.controller.Koneksi;
import isenkdoank.marikost.controller.PassingDataController;
import isenkdoank.marikost.model.Homey;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bee
 */
public class MainActivity extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public MainActivity() {
        initComponents();

        // memanggil prosedur tampil table
        tampilTable();

        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);

        // Matiin Resize / Maximize
        this.setResizable(false);

        label_username.setVisible(false);
    }

    private Data koneksi = new Data();

    private void tampilTable() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Pemilik");
        model.addColumn("Jenis Kos");
        model.addColumn("Nama Kos");
        model.addColumn("Deskripsi");
        model.addColumn("Wilayah");
        model.addColumn("Alamat");
        model.addColumn("Kontak");
        model.addColumn("Harga");

        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            // query sql untuk menampilkan semua data yang ada di table homey
            String sql = "select * from homey";
            // penghubung koneksi ke localhost mysql
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            // mengeksekusi sql
            java.sql.ResultSet res = stm.executeQuery(sql);
            // membuat perulangan untuk mencetak data yang ada didalam sql ke dalam tabel
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), 
                    res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
            }
            tabelKosan.setModel(model);
            // membuat table menjadi responsif
            tabelKosan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        } catch (Exception e) {
        }
    }

    // Inisialisasi Controller Passing Data
    private PassingDataController passdata = new PassingDataController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nama_user = new javax.swing.JLabel();
        btnProfile = new javax.swing.JLabel();
        btnPetunjuk = new javax.swing.JLabel();
        btnTentangKami = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKosan = new javax.swing.JTable();
        ads = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCariWilayah = new javax.swing.JTextField();
        btnTampilWilayah = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnFilterPenghuni = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        radiomurah = new javax.swing.JRadioButton();
        radiomahal = new javax.swing.JRadioButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marikost");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isenkdoank/marikost/assets/12c.PNG"))); // NOI18N

        nama_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nama_user.setText("Selamat Datang");

        btnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isenkdoank/marikost/assets/ea.PNG"))); // NOI18N
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });

        btnPetunjuk.setText("Petunjuk Penggunaan");
        btnPetunjuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPetunjukMouseClicked(evt);
            }
        });

        btnTentangKami.setText("Tentang Kami");
        btnTentangKami.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTentangKamiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(nama_user)
                .addGap(80, 80, 80)
                .addComponent(label_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPetunjuk)
                .addGap(18, 18, 18)
                .addComponent(btnTentangKami)
                .addGap(18, 18, 18)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nama_user)
                        .addComponent(btnPetunjuk)
                        .addComponent(btnTentangKami)
                        .addComponent(label_username))
                    .addComponent(btnProfile))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tabelKosan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKosan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelKosan.setEnabled(false);
        jScrollPane1.setViewportView(tabelKosan);

        ads.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isenkdoank/marikost/assets/bannerads.jpeg"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        jLabel3.setText("Pencarian Wilayah :");

        btnTampilWilayah.setText("Tampilkan Wilayah");
        btnTampilWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilWilayahActionPerformed(evt);
            }
        });

        jLabel4.setText("Penawaran Harga :");

        jLabel5.setText("Filter Penghuni :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Campur", "Untuk Pria", "Untuk wanita" }));

        btnFilterPenghuni.setText("Filter Penghuni");
        btnFilterPenghuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterPenghuniActionPerformed(evt);
            }
        });

        radiomurah.setText("Termurah - Termahal");
        radiomurah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomurahActionPerformed(evt);
            }
        });

        radiomahal.setText("Termahal - Termurah");
        radiomahal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiomahalActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCariWilayah)
                            .addComponent(btnTampilWilayah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFilterPenghuni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jSeparator4)
                                .addGap(279, 279, 279))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)))
                                    .addComponent(radiomurah)
                                    .addComponent(radiomahal))
                                .addGap(0, 114, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCariWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTampilWilayah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiomurah)
                .addGap(4, 4, 4)
                .addComponent(radiomahal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilterPenghuni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ads)
                        .addGap(45, 45, 45)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ads, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        String username = label_username.getText();

        if (passdata.PassDataProfil(username)) {
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Gagal Memuat Data!", "Peringatan!", 2);
        }
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnTentangKamiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTentangKamiMouseClicked
        new TentangAplikasi().setVisible(true);
    }//GEN-LAST:event_btnTentangKamiMouseClicked

    private void btnPetunjukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPetunjukMouseClicked
        new Petunjuk().setVisible(true);
    }//GEN-LAST:event_btnPetunjukMouseClicked

    private void btnTampilWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilWilayahActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Pemilik");
        model.addColumn("Jenis Kos");
        model.addColumn("Nama Kos");
        model.addColumn("Deskripsi");
        model.addColumn("Wilayah");
        model.addColumn("Alamat");
        model.addColumn("Kontak");
        model.addColumn("Harga");

        String wilayah = txtCariWilayah.getText();
        if (wilayah.equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Wilayah Tidak Boleh Kosong!");
        } else {
            //menampilkan data database kedalam tabel
            try {
                int no = 1;
                // query sql untuk menampilkan semua data yang ada di table homey
                String sql = "SELECT * FROM homey where wilayah_kost like '" + txtCariWilayah.getText() + "'";
                // penghubung koneksi ke localhost mysql
                java.sql.Connection conn = (Connection) Koneksi.getConnection();
                java.sql.Statement stm = conn.createStatement();
                // mengeksekusi sql
                java.sql.ResultSet res = stm.executeQuery(sql);
                // membuat perulangan untuk mencetak data yang ada didalam sql ke dalam tabel
                while (res.next()) {
                    model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
                }
                tabelKosan.setModel(model);
                // membuat table menjadi responsif
                tabelKosan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnTampilWilayahActionPerformed

    private void btnFilterPenghuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterPenghuniActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Pemilik");
        model.addColumn("Jenis Kos");
        model.addColumn("Nama Kos");
        model.addColumn("Deskripsi");
        model.addColumn("Wilayah");
        model.addColumn("Alamat");
        model.addColumn("Kontak");
        model.addColumn("Harga");

        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            // query sql untuk menampilkan semua data yang ada di table homey
            String sql = "SELECT * FROM homey where jenis_kost like '" + jComboBox2.getSelectedItem() + "'";
            // penghubung koneksi ke localhost mysql
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            // mengeksekusi sql
            java.sql.ResultSet res = stm.executeQuery(sql);
            // membuat perulangan untuk mencetak data yang ada didalam sql ke dalam tabel
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
            }
            tabelKosan.setModel(model);
            // membuat table menjadi responsif
            tabelKosan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnFilterPenghuniActionPerformed

    private void radiomurahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomurahActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Pemilik");
        model.addColumn("Jenis Kos");
        model.addColumn("Nama Kos");
        model.addColumn("Deskripsi");
        model.addColumn("Wilayah");
        model.addColumn("Alamat");
        model.addColumn("Kontak");
        model.addColumn("Harga");

        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            // query sql untuk menampilkan semua data yang ada di table homey
            String sql = "Select * From homey order by harga asc;";
            // penghubung koneksi ke localhost mysql
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            // mengeksekusi sql
            java.sql.ResultSet res = stm.executeQuery(sql);
            // membuat perulangan untuk mencetak data yang ada didalam sql ke dalam tabel
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
            }
            tabelKosan.setModel(model);
            // membuat table menjadi responsif
            tabelKosan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_radiomurahActionPerformed

    private void radiomahalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiomahalActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Pemilik");
        model.addColumn("Jenis Kos");
        model.addColumn("Nama Kos");
        model.addColumn("Deskripsi");
        model.addColumn("Wilayah");
        model.addColumn("Alamat");
        model.addColumn("Kontak");
        model.addColumn("Harga");

        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            // query sql untuk menampilkan semua data yang ada di table homey
            String sql = "Select * From homey order by harga desc;";
            // penghubung koneksi ke localhost mysql
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            // mengeksekusi sql
            java.sql.ResultSet res = stm.executeQuery(sql);
            // membuat perulangan untuk mencetak data yang ada didalam sql ke dalam tabel
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
            }
            tabelKosan.setModel(model);
            // membuat table menjadi responsif
            tabelKosan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_radiomahalActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Username");
        model.addColumn("Pemilik");
        model.addColumn("Jenis Kos");
        model.addColumn("Nama Kos");
        model.addColumn("Deskripsi");
        model.addColumn("Wilayah");
        model.addColumn("Alamat");
        model.addColumn("Kontak");
        model.addColumn("Harga");

        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            // query sql untuk menampilkan semua data yang ada di table homey
            String sql = "Select * From homey";
            // penghubung koneksi ke localhost mysql
            java.sql.Connection conn = (Connection) Koneksi.getConnection();
            java.sql.Statement stm = conn.createStatement();
            // mengeksekusi sql
            java.sql.ResultSet res = stm.executeQuery(sql);
            // membuat perulangan untuk mencetak data yang ada didalam sql ke dalam tabel
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
            }
            tabelKosan.setModel(model);
            // membuat table menjadi responsif
            tabelKosan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ads;
    private javax.swing.JButton btnFilterPenghuni;
    private javax.swing.JLabel btnPetunjuk;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTampilWilayah;
    private javax.swing.JLabel btnTentangKami;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel label_username;
    public javax.swing.JLabel nama_user;
    private javax.swing.JRadioButton radiomahal;
    private javax.swing.JRadioButton radiomurah;
    private javax.swing.JTable tabelKosan;
    private javax.swing.JTextField txtCariWilayah;
    // End of variables declaration//GEN-END:variables
}
